spring:
  application:
    name: jir_backend
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/projects
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres

jwt:
  secret: "my_secret_long_long_long_long_long_long_long"
  expiration: 3600000

